### PR TITLE
WIP Support for Leaflet Popup

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The content of the Popup can be any DOMWidget.

In the example below, I used a bqplot figure.

screen shot 2016-05-24 at 6 46 24 am

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cc @galleon

**Comment by SylvainCorlay** [comment]
I also realized that `displayed` events must be propagated for leaflet layers like for DOM Widgets, which I am now doing.

**Comment by galleon** [comment]
@SylvainCorlay tried it this morning it was working fine with a Text widget. Wanted to try it again and it is not working anymore. I get this error:
Error: Couldn't create a view for model id '72fbd0…s-widgets/extension.js?v=20160524134002:32043:30

**Comment by Kevin-McIsaac** [comment]
@SylvainCorlay Popups would be very useful for my current project but I can't figure out how they are used.  Can you share the code for your example above.

**Pull request closed without merging**
