### PR TITLE
#585 Added layer attribute to the SearchControl

### PR DESCRIPTION
**Pull request by sackh**
Hi @martinRenou,
I have added support for the GeoJSON layer in Search Control, now we can Search from the GeoJSON layer as well.
Please review.

search_geo-min

### CODE REVIEW

**Comment by sackh** [comment]
Hi @martinRenou 
I have made some more changes and below is the outcome :) 
Please review once you get time.
geo_searches

**Comment by martinRenou** [comment]
I will, thanks a lot

**Comment by martinRenou** [comment]
Why did you close this PR?

**Comment by sackh** [comment]
sorry, it got closed by mistake when I was trying to force sync my forked repo. I will raise a new one.

**Comment by davidbrochart** [comment]
Can't you just reopen it?

**Comment by martinRenou** [comment]
I see you open PRs from master, it would be easier to use git branches, so you can open multiple PRs at the same time.

**Pull request closed without merging**
