### PR TITLE
Test `ipyleaflet` widgets with `galata`

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Do all the example notebooks need to be committed?

**Comment by trungleduc** [comment]
> Do all the example notebooks need to be committed?

No , it's my bad

**Comment by trungleduc** [comment]
Hi all, this PR is ready for review.

**Review by davidbrochart — APPROVED** [review]

**Comment by martinRenou** [comment]
We have a slightly different setup in bqplot where we also test that updating widget's traits have the correct impact on the widget view.

I think it makes sense to do something similar for ipyleaflet, this would allow to run a cell that changes a marker position `marker.location = (53., 45.)` and take a screenshot of the map again, checking that the marker was updated as expected.

**Comment by martinRenou** [comment]
This can definitely be done in a separate PR though. That's already a great start, thank you for doing this!

**Comment by trungleduc** [comment]
> We have a slightly different setup in bqplot where we also test that updating widget's traits have the correct impact on the widget view.
> 
> See https://github.com/bqplot/bqplot/blob/master/ui-tests/tests/bqplot.test.ts
> 
> I think it makes sense to do something similar for ipyleaflet, this would allow to run a cell that changes a marker position `marker.location = (53., 45.)` and take a screenshot of the map again, checking that the marker was updated as expected.

indeed, I just add the simplest tests which try to render the available widgets of `ipyleaflet`. We can iterate to add more complicated tests after.

**Comment by martinRenou** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

@deeplook Actual tests in ipyleaflet!!!

**Pull request merged**
