### PR TITLE
Added changes to update notebook and changes Choropleth _update_data function

### PR DESCRIPTION
**Pull request by omanges**
Earlier changes caused some issue, so to improve them I am raising this PR

### CODE REVIEW

**Comment by omanges** [comment]
Hi @martinRenou the changes to change the name of the function _update_data in Choropleth class to _update_choropleth_data were causing some issue, I have reverted the changes. Please have a look.

**Comment by martinRenou** [comment]
I am not sure this is the right fix though. I'll have a look

**Comment by omanges** [comment]
Actually it was working for the GeoJSON class but when we use Choropleth class it causes
`Python: maximum recursion depth exceeded while calling a Python object` as we have @observe on both functions earlier i.e _update_data in GeoJSON and _update_choropleth_data in Choropleth. I have tested the changes for both cases now it works.

**Comment by omanges** [comment]
I am not able to understand why did the build failed @martinRenou Can you help?

**Comment by martinRenou** [comment]
I will.

Would you mind rebasing your PR though? There is a lot of noise due to merges and other commits. I would recommend not commiting to master on your branch.

In order to rebase you would need to do:
```
git remote add upstream https://github.com/jupyter-widgets/ipyleaflet.git

git fetch upstream
git rebase -i upstream/master // This will open your editor, just save and exit it should be enough
```

**Comment by omanges** [comment]
Still don't know what is causing it to timeout which makes it fail 🧐

**Comment by omanges** [comment]
It seems travis-ci is having some issue with MacOSX build: https://twitter.com/traviscistatus/status/1240725142172397568?s=20

**Comment by omanges** [comment]
@martinRenou can we see travis-ci logs why is it failing? 🧐

**Comment by martinRenou** [comment]
I'm not ignoring this, I think this should be merged before the next release.

**Comment by omanges** [comment]
Actually @martinRenou if I change the name of the function from `_update_data` to   `_update_choropleth_data` in `Choropleth` class, a `RecursionError: maximum recursion depth exceeded while calling a Python object` error is thrown if I pass style_callback in Choropleth, but if I keep it `_update_data`, it works perfectly 🧐

**Comment by omanges** [comment]
Hi @martinRenou , I think I have solved the issue.

**Comment by omanges** [comment]
Hi, @martinRenou pipeline passed https://travis-ci.org/github/jupyter-widgets/ipyleaflet/builds/666831157, but it is not showing over this PR, don't know why 🧐

**Comment by SylvainCorlay** [comment]
@omanges FYI your git committer email does not match your github registered email, which is why GitHub is not crediting these commits to you. You may want to fix this by amending your commits or by adding this email to your github account.

**Comment by omanges** [comment]
@SylvainCorlay  Really Thank you, I have added this email id to my Github account.

**Comment by martinRenou** [comment]
LGTM! I'll update the documentation

**Comment by martinRenou** [comment]
I reviewed this PR too quickly. I did not see it was changing the GeoJSON class. This is breaking GeoJSON, even though it fixes the Choropleth. I'll come up with a better fix.

**Pull request merged**
