### PR TITLE
Add Leaflet.Path.Transform

### PR DESCRIPTION
**Pull request by davidbrochart**
This PR gives the possibility to transform (i.e. rotate and scale) and drag e.g. polygons. It vendors [Leaflet.Path.Transform](https://github.com/w8r/Leaflet.Path.Transform) and [Leaflet.Path.Drag](https://github.com/w8r/Leaflet.Path.Drag) because of bugs that could not be fixed upstream.
The `examples/Transform.ipynb` notebook illustrates the API.

### CODE REVIEW

**Comment by davidbrochart** [comment]
ping @martinRenou @SylvainCorlay

**Comment by davidbrochart** [comment]
Leaflet.Path.Transform and Leaflet.Path.Drag are not vendored any more. I forked them, merged, fix and published them: https://www.npmjs.com/package/leaflet-transform

**Comment by martinRenou** [comment]
Is it ready to be merged?

**Comment by davidbrochart** [comment]
Yes!

**Pull request merged**
