### PR TITLE
Fix for KeyError: 'popup_anchor' and other traits of Icon

### PR DESCRIPTION
**Pull request by sackh**
Signed-off-by: Kharude, Sachin <sachin.kharude@here.com>
Fix for issue #633

### CODE REVIEW

**Comment by martinRenou** [comment]
This is weird. It should not behave that way IMO. The `default_value` is set to `None`, and we allow the `None` value. Also, `null` is the default in LeafletJS, so I think we should respect that.

It might be an issue with traitlets itself.

I agree this issue should be fixed, I am just unsure with this fix.

**Comment by sackh** [comment]
One more observation is that when we pass parameters `minlen=2, maxlen=2` it fails even though default_value is set to `None`, and we allow the `None`,  but if we remove the `minlen=2, maxlen=2` then it works. It looks like an issue with traitlets when we pass params `minlen=2, maxlen=2`

**Comment by martinRenou** [comment]
I guess it's unlikely that we can fix Traitlets and get a release soon.

What we could do is implement our own traitlets validator, checking the length ourselves. What do you think?

Thanks for spotting this issue BTW, we should fix this issue before making a release.

**Comment by sackh** [comment]
Yes, Traitlets validator is a good idea. shall we use `validate` decorator from Traitlets itself or any other approach?

**Comment by martinRenou** [comment]
The `validate` decorator is fine I guess :)

**Comment by sackh** [comment]
Ok, I will make these changes and raise the PR.

**Comment by SylvainCorlay** [comment]
Thanks for finding a workaround!

**Comment by martinRenou** [comment]
Why did you discard the comments @SylvainCorlay ?

**Comment by martinRenou** [comment]
I guess you missed them. I opened a PR to fix this. It appears to be a Traitlets bug though.. Maybe we should try to fix it upstream.

**Pull request merged**
