### PR TITLE
Changes to enable float zoom levels

### PR DESCRIPTION
**Pull request by omanges**
These changes fix the issue raised in https://github.com/jupyter-widgets/ipyleaflet/issues/591

### CODE REVIEW

**Comment by martinRenou** [comment]
LGTM! I can squash and merge.

**Comment by martinRenou** [comment]
The CI failure seems unrelated, but I am not sure

**Comment by martinRenou** [comment]
Yes it's unrelated. It might be a new flake8 rule. Let's fix it in another PR.

**Comment by davidbrochart** [comment]
`zoom_delta` and `zoom_snap` and not used on the JS side?

**Comment by martinRenou** [comment]
It is :) It will be auto-magically handled by ipyleaflet, being an option (`0=True`).

**Comment by davidbrochart** [comment]
Did you check that it works fine? I tried on a vector tile layer and it doesn't seem to work.

**Comment by omanges** [comment]
Yes, it is working for me.
[image: image.png]

**Comment by martinRenou** [comment]
> Did you check that it works fine? I tried on a vector tile layer and it doesn't seem to work.

Actually you're right. Handling options changes is not implemented on the `Map`. This should be fixed.

**Comment by davidbrochart** [comment]
@omanges it looks like it works for everything but a vector tile layer.

**Comment by davidbrochart** [comment]
My bad, I didn't pass the options on the `Map` but on the layer!
Everything's good, sorry!

**Comment by omanges** [comment]
Great, It works for you as well!!!

**Pull request merged**
