### PR TITLE
Add visible attribute to GeoJSON layer

### LINKED ISSUE #827: Changing GeoJSON/GeoData layer visibility programmatically
Unlike TileLayer, a GeoJSON/GeoData layer does not have the `visible` attribute. Is there a way to turn a GeoJSON/GeoData layer on/off programmatically without using the LayersControl? Thanks.

### PR DESCRIPTION
**Pull request by davidbrochart**
Fixes #827.

### CODE REVIEW

**Comment by giswqs** [comment]
Wow, this is nice! I have been waiting for this feature for a while. Thank you.

**Comment by davidbrochart** [comment]
I've been trying to implement the `visible` attribute using `opacity` and `fillOpacity` before reaching this solution. My conclusion is that it was a mess, because there are global opacities and feature opacities, and once you set the global opacity to 0 you cannot revert.

**Comment by giswqs** [comment]
I would love to contribute. I really need to learn JavaScript. Once this PR is merged and the `visible` attribute is working, I will see if I can make the `opacity` attribute work.

**Comment by jasongrout** [comment]
The docs test is failing for unrelated reasons (404 on a resource)

**Comment by giswqs** [comment]
I just tested v0.17.0 and the GeoJSON `visible` attribute. Just figured out that you can actually control the `style` attribute to set opacity. So it is now possible to change the GeoJSON layer opacity interactively. 

```python
g.style={'fillOpacity': 0.5, 'opacity': 1}
```
image

**Comment by davidbrochart** [comment]
So this is not working since v0.17, right? I guess it was already working before.

**Comment by giswqs** [comment]
@davidbrochart It is working well. I was just saying that the geojson layer opacity can be changed using the `style` attribute, so I don't need to submit a PR to mess up the JS code.

**Comment by giswqs** [comment]
I did not know that `style` attribute before v0.17.0. I was working on the PR and then realized that the `style` attribute is exactly what I needed to change layer opacity interactively, so no PR from me.

**Comment by davidbrochart** [comment]
Great, I just meant that this is not particularly true since v0.17, the `style` attribute was there before.

**Pull request merged**
