### PR TITLE
Make group layers work

### LINKED ISSUE #37: LayerGroup not rendering?
I wanted to use LayerGroup()  to create a  layer of markers, however I can't get it to render on the map. 

After extensive reading of the python and java script to understand how this might be done, my code looks like this.

```
center = [-33.858840, 151.206701]
zoom = 0
map_nsw = ll.Map(default_tiles=ll.TileLayer(opacity=1.0),
           center=center, zoom=zoom)

lg = ll.LayerGroup()
mark = ll.Marker(location=center)
c = ll.Circle(location=center)
lg.layers = [mark, c]
map_nsw += lg
map_nsw
```

What have I missed or isn't LayerGroup implemented.

### PR DESCRIPTION
**Pull request by Kevin-McIsaac**
This fixes #37

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks, this look good to me.

Minor remarks:
 - could you clear the output of the example notebooks?
 - It seems that you did not set up git with the same email as your GitHub account, so that you are not properly credited with these commits.

Hence I recommend that you rebase your PR and re-commit these with the proper git config.

**Comment by Kevin-McIsaac** [comment]
@SylvainCorlay as I'm a git n00bm, I'm not sure if I got this right

I've set my user name and email address, then ran  "git rebase" on the LayerGroup branch. Did this fix the problems? If not, what else do I need to do?

**Comment by SylvainCorlay** [comment]
Your git config is OK now. (You can see your profile picture by your last commit). The two earlier commits are not correctly credited to you .

You can change that (if you want) by amending the past commit author and committer names but I understand it is cumbersome if you are not used to it.

I will review your changes tomorrow.

Regarding the notebook, it seems that you are using some jupyter extensions that add things to the metadata.

**Comment by SylvainCorlay** [comment]
Closing as it is being fixed in an up-to-date branch. You are credited for the commit in the new PR.

**Pull request closed without merging**
