### PR TITLE
Add support for font-awesome icons in Markers

### PR DESCRIPTION
**Pull request by martinRenou**
icons2

Related to https://github.com/jupyter-widgets/ipyleaflet/issues/83, it does not add automatic support in the GeoJSON layer though.

### CODE REVIEW

**Comment by martinRenou** [comment]
@davidbrochart That would be awesome if you could look at this one too! :)

I think we should do a release tomorrow with all those new changes/bug fixes

**Comment by davidbrochart** [comment]
Awesome!

**Comment by martinRenou** [comment]
I guess I can take this as approval :P

**Comment by davidbrochart** [comment]
:+1:

**Pull request merged**
