### PR TITLE
Update changelog for 0.17 and reintroduce embedded jupyterlite

### PR DESCRIPTION
**Pull request by jasongrout**
Update changelog for 0.17

### CODE REVIEW

**Comment by jasongrout** [comment]
I'm updating the retrolite example in the docs here too, and with the current PR, when I execute

```
import piplite
await piplite.install('ipyleaflet', keep_going=True);
```
I get an error:

```
ValueError: Couldn't find a pure Python 3 wheel for: 'tornado>=6.1', 'tornado>=4.1', 'pyzmq>=13', 'tornado>=6.1.0', 'pyzmq>=17', 'argon2-cffi-bindings'
```
@martinRenou - do you happen to know what is going on? Of course pyzmq doesn't have a pure python package - how do I work around that?

**Comment by jasongrout** [comment]
Possibly relevant issues: https://github.com/jupyterlite/jupyterlite/issues/620 (discussing micropip instead of piplite),

**Comment by jasongrout** [comment]
Here's what I think is going on:

As mentioned [here](https://github.com/jupyterlite/jupyterlite/issues/551#issuecomment-1067453309), pyolite ships with a few shim packages, including [widgetsnbextension](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/src/_pypi.ts#L6). Our version of jupyterlite is too old, and is shipping an old version of widgetsnbextension. So we need to just upgrade our jupyterlite version, and delete the widgetsnbextension dependency from our jupyterlite configuration.

Is this our widgetsnbextension -> notebook dependency causing us issues? Luckily that is going away in ipywidgets 8.

**Comment by jasongrout** [comment]
@martinRenou - I think this is ready for review now. If you're okay with it, I'd like to cut the 0.17 release tomorrow, unless you have something you really think should go in that isn't in already.

**Comment by jasongrout** [comment]
> I'd like to cut the 0.17 release tomorrow

(or I wouldn't be sad if someone else wanted to cut a release, just saying that I'm happy to volunteer to do it)

**Comment by martinRenou** [comment]
> Is this our widgetsnbextension -> notebook dependency causing us issues? Luckily that is going away in ipywidgets 8.

Yes, this is the `widgetsnbextension -> notebook -> tornado` requirement which causes issues with pip install. Concerning the conda installation (for xeus-python), the fact that the widgetsnbextesion feedstock was not noarch was also causing issue.

**Review by martinRenou — APPROVED** [review]
Thanks!!

**Comment by martinRenou** [comment]
For the release, I usually do:

1. `git clean -fdx`
2. Update `ipyleaflet/_version.py`, `setup.py` and `package.json` versions (see https://github.com/jupyter-widgets/ipyleaflet/commit/48f3cb68cd07e6c4ae7b353a17861e4e51ca4471)
3. (on master) `git commit -m "Release 0.17.0"`
4. (on master) `git tag 0.17.0`
5. `git push upstream master` (upstream being https://github.com/jupyter-widgets/ipyleaflet)
6. `git push upstream 0.17.0`
7. `python -m build`
8. `twine upload dist/*`
9. `yarn install && yarn run build && yarn publish` (yarn prompt for the new version, I give the same as what is already in the `package.json`)

**Pull request merged**
