### PR TITLE
add gaode

### PR DESCRIPTION
**Pull request by xiangmeng4geo**
Add gaode basemap

### CODE REVIEW

**Comment by davidbrochart** [comment]
Thanks! It looks like your commit isn't linked to your GitHub account. Maybe you want to fix it before merging?
See https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by xiangmeng4geo** [comment]
> Thanks! It looks like your commit isn't linked to your GitHub account. Maybe you want to fix it before merging?
> See https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

Maybe I forgot to verify my email before. It has been fixed.  If it's still a problem with account, leave it alone.

**Comment by davidbrochart** [comment]
Do you want to reopen this PR and force-push a new commit?

**Comment by xiangmeng4geo** [comment]
> Do you want to reopen this PR and force-push a new commit?

yes

**Comment by davidbrochart** [comment]
Do you want to push a new commit with your fixed GitHub ID?

**Comment by martinRenou** [comment]
It might not be required to fix the commit, you might just need to add your meng******@moji.com address to your Github account, it was the address used during the commit.

I recall there is no need for validation for it to work (I did it once with an address that did not exist anymore and it worked).

**Comment by xiangmeng4geo** [comment]
I use global git email on my working computer,which been set to our company git address,so I think that`s all right.

**Comment by davidbrochart** [comment]
Thanks!

**Pull request merged**
