### PR TITLE
Add bounds attribute to TileLayer

### LINKED ISSUE #888: Constrain bounds of TileLayer
Would it be possible to add a property to the `TileLayer` that will constrain its bounds? 

The lack of constraint poses a problem when accessing a tile server I have that serves individual rasters (small coverage, not global). The `TileLayer` continues to make requests from my tile server anytime I zoom out/view outside the data bounds, overloading my tile server which is just returning a bunch of transparent PNGs.

The logic I'm looking for:

```py
t = TileLayer(
    url="https://mytileserver.com/tiles/{z}/{x}/{y}.png?projection=EPSG:3857",
    # Do not request tile outside of these bounds (bottom, top, left, right)
    bounds=[37.40679, 38.080379, -122.759396, -122.065103],
)
```

From what I can tell, the leaflet JS tileLayer does have an option for `bounds` that is inherited from gridLayer but this does not seem to be wrapped in `ipyleaflet`. Ref https://leafletjs.com/reference.html#tilelayer

Example data:

Screen Shot 2021-11-20 at 8 33 19 PM

-------

Additional context:

- https://github.com/banesullivan/flask-tileserver / https://github.com/jupyter-widgets/ipyleaflet/issues/234#issuecomment-974716145
- https://github.com/ResonantGeoData/ResonantGeoData/pull/603

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #888

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure about the UI test failure, any idea @trungleduc ?

**Comment by trungleduc** [comment]
it looks like  some texts on the map have changed

- Expected map
SplitMapControl-expected

- Rendered map
SplitMapControl-actual

- Diff

SplitMapControl-diff

**Comment by trungleduc** [comment]
You can update `SplitMapControl-linux.png` file with the rendered map to make the tests pass, we can remove this test if the screenshot keeps changing.

**Comment by davidbrochart** [comment]
Thanks Trung, I uploaded the rendered snapshot. Let's hope the base map doesn't change too often.

**Comment by martinRenou** [comment]
Thanks! You also need to change the Javascript model

**Comment by davidbrochart** [comment]
Thanks! Interestingly, it was already working without it.

**Comment by martinRenou** [comment]
Yes, it's only used in some cases when the widget is embedded.

**Comment by davidbrochart** [comment]
@trungleduc where are the UI test assets uploaded? I cannot find them.

**Comment by trungleduc** [comment]
https://github.com/jupyter-widgets/ipyleaflet/actions/runs/1605786157, Artifacts section

**Comment by trungleduc** [comment]
I think we should update the `SplitMapControl.ipynb` notebook to move the map somewhere else

**Comment by davidbrochart** [comment]
I removed the update of the rendered split map, tests are passing now.
I'm wondering if the tiles are not still loading when the snapshot is made, e.g. maybe we change the zoom and we don't wait enough?

**Comment by martinRenou** [comment]
Did you see there was a very nice splitmap widget on Github for checking the splitmap screenshot?


https://user-images.githubusercontent.com/21197331/146900522-6819aa81-4123-4da6-8f2d-27fd67fbeb28.mp4

**Pull request merged**
