### PR TITLE
Added WKT layer feature to add WKT data on map

### PR DESCRIPTION
**Pull request by sackh**
Signed-off-by: Kharude, Sachin <sachin.kharude@here.com>

### CODE REVIEW

**Comment by sackh** [comment]
@davidbrochart  - please review this. I have added WKT support as mentioned in #669

**Comment by davidbrochart** [comment]
Thanks. I'm wondering if we should rather use [shapely](https://shapely.readthedocs.io/en/latest/manual.html) to do these conversions on the Python side, and always use a `GeoJSON` layer.

**Comment by sackh** [comment]
Yes, shapely would be good for `wkt` to `GeoJSON` conversion, I will check whether it supports other formats as well.

**Comment by sackh** [comment]
closing this I have opened new PR #679 using shapely to convert WKT to GeoJSON on python side.

**Pull request closed without merging**
