### PR TITLE
Add localtileserver to related projects

### PR DESCRIPTION
**Pull request by banesullivan**
Adds localtileserver to the related projects to help people visualize their large geospatial rasters with ipyleaflet: https://github.com/banesullivan/localtileserver

### CODE REVIEW

**Comment by martinRenou** [comment]
It looks like the link does not render well : https://ipyleaflet--976.org.readthedocs.build/en/976/

**Comment by banesullivan** [comment]
🤦🏻‍♂️ the link should be fixed now

**Comment by martinRenou** [comment]
Thanks! 😊

**Comment by martinRenou** [comment]
UI tests failure is unrelated.

Thanks!

**Pull request merged**
