### PR TITLE
Add min_native_zoom and max_native_zoom for TileLayer

### PR DESCRIPTION
**Pull request by kgiacobbi**
Add options for TileLayer:
- min_native_zoom 
- max_native_zoom

maxNativeZoom: 
Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.

minNativeZoom: 
Minimum zoom number the tile source has available. If it is specified, the tiles on all zoom levels lower than minNativeZoom will be loaded from minNativeZoom level and auto-scaled.

### CODE REVIEW

**Comment by martinRenou** [comment]
Thanks! I'd be really happy to merge it, but there seem to have been an issue on the repo (a force push on master maybe? :S). Because commits from #366 seems to have disappeared from the repo. That's why they appear on your PR.

I'm not sure what to do, I'll try fixing everything

**Comment by kgiacobbi** [comment]
Sorry, i can re-fork the actual state and do it again if you want.

**Comment by martinRenou** [comment]
No it's not your fault, I think it's mine. I must have done something wrong. I'll try to fix it.

**Comment by martinRenou** [comment]
Closed in favor of #382 (You are still the author of the commits, I only cherry-picked them)

**Comment by kgiacobbi** [comment]
No problems. :+1:

**Pull request closed without merging**
