### PR TITLE
Add Travis installation check

### LINKED ISSUE #377: Enable CI
We should enable CI with Travis. Even if we have no test **yet**, it would prevent this kind of issues #375.

### PR DESCRIPTION
**Pull request by martinRenou**
This will fix #377

### CODE REVIEW

**Comment by jtpio** [comment]
Are there any reasons for not choosing an alternative like GitHub Actions when starting "fresh"? (just curious)

Maybe because of conda?

**Comment by martinRenou** [comment]
No reason, honestly. I know Travis, I used it.

> Maybe because of conda?

What do you mean? Can you not use conda with Github Actions?

**Comment by jtpio** [comment]
No worries, it was just tempting to ask since core ipywidgets moved to GH Actions.

> Can you not use conda with Github Actions?

It is possible (used for Voila), but it's not as nice and out-of-the-box as the `setup-python` start action for example.

**Comment by martinRenou** [comment]
Ok. Yes, it might make sense to use Github Actions then.

**Pull request merged**
